<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Queuing</name>
   <tag></tag>
   <elementGuidId>6b61d21c-d55c-48c1-8c03-e55563a991e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button.btn.btn-secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='food']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d389f3a3-467f-4dca-b50c-c420eb9ca0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btn btn-secondary</value>
      <webElementGuid>945b6a4b-df09-49d9-9859-6f32322def47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Queuing </value>
      <webElementGuid>12255849-0d95-47a1-adda-41ad644c49ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;food&quot;)/a[@class=&quot;button btn btn-secondary&quot;]</value>
      <webElementGuid>2ce93d12-0f2f-40d2-8c86-cdac352db424</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='food']/a</value>
      <webElementGuid>61ea5533-f4ff-4c46-a6fd-dd30d0220b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Queuing')]</value>
      <webElementGuid>ccd88d57-b3b5-4800-904b-b70cce165f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cooking'])[1]/preceding::a[1]</value>
      <webElementGuid>f7a80b2b-149d-4581-8c4d-946fba92dd81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deliver'])[1]/preceding::a[2]</value>
      <webElementGuid>942f68de-ec81-41cb-a9f6-3616d46177ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Queuing']/parent::*</value>
      <webElementGuid>baf9e33c-2a2e-4a93-ac39-c922644f7a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>339be302-ecac-41df-b146-e5e25551f49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Queuing ' or . = 'Queuing ')]</value>
      <webElementGuid>e787aaf6-0589-4a8c-9a11-90e7ab7b8fe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
