<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_add to cart</name>
   <tag></tag>
   <elementGuidId>fd0bbb36-753a-4133-ab5b-d4576597ebb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@name='buttonFood'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9273eed4-8250-465b-9f63-5870f7df7ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>buttonFood</value>
      <webElementGuid>bfaa4e72-b872-4ee8-8df5-0edc35d0cce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btn</value>
      <webElementGuid>45382b3c-7f4e-41b9-9d12-2c595090a5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c1b73975-2fd5-408d-931c-c1cf5898e7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.form.submit()</value>
      <webElementGuid>2aa98196-60f9-401f-8207-84e8b7f7ce76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ac51704e-087a-4937-9262-bf0d8c17ceef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>add to cart</value>
      <webElementGuid>07d3cc9a-e567-44c5-bcb0-9db64c83bb45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;box-container&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;content&quot;]/form[1]/button[@class=&quot;button btn&quot;]</value>
      <webElementGuid>eb606371-de50-4968-a164-b2377c7fc193</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name='buttonFood'])[2]</value>
      <webElementGuid>f06e0577-53d4-4d92-b7cf-2dfcc252cabe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='menu']/div/div[2]/div[2]/form/button</value>
      <webElementGuid>79c2c5ed-2e57-4431-bdbb-bbd9fd1a1d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donut but no hole in the middle'])[1]/following::button[1]</value>
      <webElementGuid>76293e6d-b0a2-46f0-8f3f-485629a5216a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add to cart'])[1]/following::button[1]</value>
      <webElementGuid>41516305-44e6-498c-9b8b-55120bbbb6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I think this is cat meat'])[1]/preceding::button[1]</value>
      <webElementGuid>4eed7327-7567-4203-ad8b-6001a2bd8f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add to cart'])[3]/preceding::button[1]</value>
      <webElementGuid>f0509616-16cf-4cfb-b6d1-d11a66595f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/form/button</value>
      <webElementGuid>1f12f47e-a9a4-4da4-851f-39d9ff654fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'buttonFood' and @type = 'checkbox' and (text() = 'add to cart' or . = 'add to cart')]</value>
      <webElementGuid>ea7ab790-40ca-4149-9062-62b2c016a097</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
