<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Donut but no hole in the middle</name>
   <tag></tag>
   <elementGuidId>710c1765-38a0-469a-a24e-28fecef3a5c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//h3[@name='foodName'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>14a30c76-63ab-48b4-99c4-ea2734352935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>foodName</value>
      <webElementGuid>795d2b68-c357-4d41-96fb-fa0c99dc4f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Donut but no hole in the middle</value>
      <webElementGuid>fe9b71ad-eac0-4882-8970-dd7afb5c7a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;box-container&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;content&quot;]/h3[1]</value>
      <webElementGuid>c51df7f9-6b43-4a88-9f01-00196c5ecc12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//h3[@name='foodName'])[2]</value>
      <webElementGuid>a936bbd5-a247-4750-92a7-d23c8e467c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='menu']/div/div[2]/div[2]/h3</value>
      <webElementGuid>e50bd3f0-08c2-4133-918a-1bbbc0c42447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add to cart'])[1]/following::h3[1]</value>
      <webElementGuid>a80482ff-b0e8-4a4d-b0d6-360be7d01859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dog Meat'])[1]/following::h3[1]</value>
      <webElementGuid>7b7a1786-b760-40ec-a8f8-e61bf9455c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add to cart'])[2]/preceding::h3[1]</value>
      <webElementGuid>43f96b93-9046-41d3-8764-1d5e7b404b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I think this is cat meat'])[1]/preceding::h3[1]</value>
      <webElementGuid>9cea0d93-594a-4fa1-a038-bce9b99be155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Donut but no hole in the middle']/parent::*</value>
      <webElementGuid>76690c36-42ac-4540-99b1-ad7e0c9e8d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/h3</value>
      <webElementGuid>88c535b6-35ab-42ac-b5d7-4981b91801e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@name = 'foodName' and (text() = 'Donut but no hole in the middle' or . = 'Donut but no hole in the middle')]</value>
      <webElementGuid>e2a2df9d-afc7-4413-bdda-1fd590fd50c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
