<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_300 THB</name>
   <tag></tag>
   <elementGuidId>8083ceb7-7c6b-4824-97b4-2831dcbf0e29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@name='foodPrice'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dcc6a976-e1a6-4af8-a934-ac299d02ffb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>74cddf50-cd8f-4e38-9f17-f93f93b9481c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>foodPrice</value>
      <webElementGuid>de21c966-c4c8-4b1b-acb5-2d9c4f4c5744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>300 THB</value>
      <webElementGuid>1747666f-7002-46d7-82b0-49f4b0d88e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;box-container&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;content&quot;]/span[@class=&quot;price&quot;]</value>
      <webElementGuid>267acefc-e074-42b1-8ac9-0baa3079818f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@name='foodPrice'])[2]</value>
      <webElementGuid>e634a40b-195a-452c-a417-4b8b9eb35a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='menu']/div/div[2]/div[2]/span</value>
      <webElementGuid>f639882c-81c6-407a-a00a-2057369251f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add to cart'])[2]/following::span[1]</value>
      <webElementGuid>71c2178e-f0b0-4a45-95b2-8394c16bad2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donut but no hole in the middle'])[1]/following::span[1]</value>
      <webElementGuid>59a27920-0505-4670-aaa4-d2b8878b6bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I think this is cat meat'])[1]/preceding::span[1]</value>
      <webElementGuid>33099813-f0e5-44e7-bef4-b4b755193753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add to cart'])[3]/preceding::span[1]</value>
      <webElementGuid>cfb2e93f-5c58-419a-aed8-6d138372d507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='300 THB']/parent::*</value>
      <webElementGuid>02e72648-a2ff-493c-9359-9d5e2bdd251c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span</value>
      <webElementGuid>070bc747-fcd0-4dcc-bee5-970ae872eea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@name = 'foodPrice' and (text() = '300 THB' or . = '300 THB')]</value>
      <webElementGuid>96c9408d-fce4-4c8c-ae5b-46d10edf76be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
