<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_-</name>
   <tag></tag>
   <elementGuidId>7dfca218-3545-49b0-af9a-6eabcfafe47d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@name='minus'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>de30ec3f-a78f-4a9b-bcad-eef2cd198d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>minus</value>
      <webElementGuid>15cc6aac-fca3-4098-a7f8-e661ae9e7c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.form.submit()</value>
      <webElementGuid>cd4a4913-31d1-44e5-a9c6-bf73fb53e2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>05bd0b61-5b25-4eac-8f74-360253930451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>642a04a6d66aa63f6dbba8ec</value>
      <webElementGuid>c522aaf4-6224-4fea-bb8c-8fd6136f89cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>1c4d6709-6a8c-4cd5-b644-23624a0c52b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cartItems&quot;)/form[6]/button[2]</value>
      <webElementGuid>c0fea279-fab7-4fa6-994e-b3f19b6d31c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name='minus'])[6]</value>
      <webElementGuid>28e61144-5a8a-448e-b76d-dec99dbe8671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cartItems']/form[6]/button[2]</value>
      <webElementGuid>d9dbb00c-fcc3-4977-a08f-3ba4882295cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[6]/following::button[1]</value>
      <webElementGuid>2fd152d9-6518-41c3-bfd9-abcf1abec170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity: 2'])[1]/following::button[2]</value>
      <webElementGuid>a0c96c45-8de7-4644-9d56-700594cf583a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foods'])[1]/preceding::button[3]</value>
      <webElementGuid>82cfedf1-9455-4229-8a09-9be26e21b5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dog Meat'])[1]/preceding::button[3]</value>
      <webElementGuid>6f490775-dc94-4c47-84ba-776f6b3c3ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[6]/button[2]</value>
      <webElementGuid>d4a27cae-7585-4355-aca2-e4ce44cb3027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'minus' and @type = 'checkbox' and (text() = '-' or . = '-')]</value>
      <webElementGuid>6feebf20-8594-407b-b932-a9d45d7da974</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
